local config={
    repo={
        export=true,
        palettes={
            true,
            true,
            true,
            false
        },
        versions={
            '1.1b6',
            '0.07',
            '0.02',
            '0'
        }
    },
    custom={
        export=true,
        dir='D:/Games/Roguelikes/powder118_win/',
        palette='master',
        override=true,
        equipment=true,
        extra_alphabets=true,
        alph_in={
            'cheepicus',
            'ibm_cga_thin',
            'minecraft',
            'msx',
            'textmachine_handwriting'
        },
        alph_out={
            'brass',
            'classic',
            'heavy',
            'light',
            'shadow'
        }
    }
}
